language: php
sudo: false

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer install

script:
  - phpunit
