<?php

namespace App\Providers;

use App\Packages\Loggers\BitcoinLogger;
use Illuminate\Support\ServiceProvider;

class LogServiceProvider extends ServiceProvider
{
    /**
     * Indicates if loading of the provider is deferred.
     *
     * @var bool
     */
    protected $defer = true;

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton(BitcoinLogger::class, function($app) {
            return new BitcoinLogger;
        });
    }

    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
        return [BitcoinLogger::class]; // TODO: Change the autogenerated stub
    }
}
